apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: yogesh
  region: ap-southeast-1
  version: "1.32"

iam:
  withOIDC: true

privateCluster:
  enabled: true
  additionalEndpointServices:
    - "autoscaling"

vpc:
  id: "vpc-04d249e3da0ab7d29"
  subnets:
    public:
      public-one:
        id: "subnet-06882b8514c158855"
    private:
      private-one:
        id: "subnet-076004e48b8440aa5"

managedNodeGroups:
  - name: mischief
    instanceType: t2.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
    subnets:
      - private-one
    privateNetworking: true
    labels:
      nodegroup-type: frontend-app
    taints:
      - key: frontend
        value: "true"
        effect: NoSchedule
    volumeSize: 20
    volumeType: gp2
    updateConfig:
      maxUnavailable: 1
    iam:
      withAddonPolicies:
        autoScaler: true
        propagateASGTags: true

  - name: mischief-2
    instanceType: t2.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 7
    subnets:
      - private-one
    privateNetworking: true
    labels:
      nodegroup-type: backend-app
    taints:
      - key: backend
        value: "true"
        effect: NoSchedule
    volumeSize: 20
    volumeType: gp2
    updateConfig:
      maxUnavailable: 1
    iam:
      withAddonPolicies:
        autoScaler: true
        propagateASGTags: true
